---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openm
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openm
  template:
    metadata:
      labels:
        app: openm
      annotations:
        ad.datadoghq.com/openm.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "openmetrics_endpoint": "http://192.168.64.99:30000/metrics",
                  "namespace": "openm",
                  "metrics": [
                    ".*"
                  ]
                }
              ]
            }
          }           
    spec:
      containers:
      - name: openm
        image: openm:latest
        imagePullPolicy: Never
      - name: nginx
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openm
  name: openm
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: openm
  type: NodePort