---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openm
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openm
  template:
    metadata:
      labels:
        app: openm
    spec:
      containers:
      #- name: container
      #  image: saphoooo/openm:latest
      - name: container
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openm
  name: openm
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: openm
  type: NodePort