apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: tambi
build:
  artifacts:
  - image: saphoooo/tambi
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - tambi.yaml